In [11]:
from unicodedata import east_asian_width
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

In [34]:
df = pd.read_csv('CleanDF.csv')
df.set_index(df['date'], inplace=True)
del df['date'], df[df.columns[0]]
df.head()

,PM10,PM2.5,O3,NO,NO2,NOx,SO2,CO,PRS,RH,TOUT,SR,WSR,WDR,RQINF
date,,,,,,,,,,,,,,,
2018-01-01 00:00:00.000,20.0,25.0,11.0,9.7,2.9,12.0,5.6,0.92,721.5,89.0,7.94,0.0,13.0,44.0,0.0
2018-01-01 01:00:00.000,20.0,25.0,11.0,9.7,2.9,12.0,5.6,0.92,721.5,89.0,7.94,0.0,13.0,44.0,0.0
2018-01-01 02:00:00.000,29.0,25.0,10.0,11.6,5.1,16.7,5.6,0.92,721.5,88.0,7.39,0.0,13.0,43.0,0.0
2018-01-01 03:00:00.000,26.0,18.0,8.0,9.5,4.3,13.6,5.6,0.92,721.5,90.0,6.37,0.0,13.0,48.0,0.0
2018-01-01 04:00:00.000,15.5,11.0,8.0,10.7,4.5,15.0,5.6,0.92,721.5,94.0,5.42,0.0,13.3,48.0,0.0

### Estandarizando

In [37]:
s_array = StandardScaler().fit_transform(df)
sdf = pd.DataFrame(s_array, columns = df.columns)
sdf.head()

,PM10,PM2.5,O3,NO,NO2,NOx,SO2,CO,PRS,RH,TOUT,SR,WSR,WDR,RQINF
0,-1.368942,0.317277,-0.970863,0.029827,-0.167195,-0.216449,-0.186491,-0.316054,2.251493,1.483321,-2.193661,-0.699757,1.895538,-0.979951,-0.068882
1,-1.368942,0.317277,-0.970863,0.029827,-0.167195,-0.216449,-0.186491,-0.316054,2.251493,1.483321,-2.193661,-0.699757,1.895538,-0.979951,-0.068882
2,-1.067367,0.317277,-1.019227,0.157357,-0.085660,-0.105645,-0.186491,-0.316054,2.251493,1.433957,-2.272433,-0.699757,1.895538,-0.999172,-0.068882
3,-1.167892,-0.210328,-1.115955,0.016403,-0.115309,-0.178729,-0.186491,-0.316054,2.251493,1.532686,-2.418518,-0.699757,1.895538,-0.903067,-0.068882
4,-1.519729,-0.737932,-1.115955,0.096948,-0.107897,-0.145723,-0.186491,-0.316054,2.251493,1.730146,-2.554578,-0.699757,1.999313,-0.903067,-0.068882